### ISSUE TITLE
no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beata1"

### ISSUE THREAD

**Issue by marknefedov** [yugabyte/yugabyte-operator#48]
apiextensions.k8s.io/v1beata1 is deprecated in k8s v1.22.0 version.
https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/#:~:text=The%20beta%20CustomResourceDefinition%20API%20(apiextensions.k8s.io/v1beta1)
![image](https://user-images.githubusercontent.com/20001291/173388780-00b29daf-16f0-438b-a339-9ecc0bea8808.png)

**Comment by miran248** [comment]
See #24
It contains a working PR, which was not merged.
